blueprint:
  name: Ikea STYRBAR remote on/off v1.1 - by xStacke
  description: STYRBAR remote blueprint for dimming and toggling lights
  domain: automation
  # Changelog
  # 17-12-23 | split blueprint into a toggle and on/off version for lights
  # 27-12-23 | Added inputs for the left and right button, short press only currently
  # 14-01-24 | Fixed staggered dimming, transition is now smooth
  #

  # User inputs while deploying the blueprint
  input:
    remote:
      name: Select STYBAR switch
      description: Choose the STYBAR you want to use for this automation
      selector:
        device:
          manufacturer: IKEA of Sweden
          multiple: false
    target_light:
      name: Lights
      description: The lights you want to control with the remote
      selector:
        target:
          entity:
            - domain:
                - light
    left_short:
      name: Action for the left button (Optional) (short press)
      description: Action to run on short right button press.
      default: []
      selector:
        action: {}
    right_short:
      name: Action for the right button (Optional) (short press)
      description: Action to run on short right button press.
      default: []
      selector:
        action: {}

# Triggers for the blueprint to function
trigger:
  # turn on pressed and off pressed
  - platform: device
    device_id: !input remote
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    id: turn-on
  - platform: device
    device_id: !input remote
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    id: turn-off
  # Dim up long press and release
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_up
    id: dim-up-pressed
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_release
    subtype: dim_up
    id: dim-up-released
  # Dim down long press and release
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_down
    id: dim-down-pressed
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_release
    subtype: dim_down
    id: dim-down-released
  # Left press
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: left
    id: left-pressed
  # right press
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: right
    id: right-pressed

# Actions for the blueprint to take
action:
  - choose:
      - conditions:
          - condition: trigger
            id:              
              - turn-on
        sequence:
          - service: light.turn_on
            data: {}
            target: !input target_light
        alias: turn on Lights
      - conditions:
          - condition: trigger
            id:
              - turn-off
        sequence:
          - service: light.turn_off
            data: {}
            target: !input target_light
        alias: turn off Lights

      # Dim up long press
      - conditions:
          - condition: trigger
            id:
              - dim-up-pressed
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: 1
              while:
                - condition: trigger
                  id:
                    - dim-up-pressed

      # Dim down long press
      - conditions:
          - condition: trigger
            id:
              - dim-down-pressed
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: 1
              while:
                - condition: trigger
                  id:
                    - dim-down-pressed

      # left press
      - conditions:
          - condition: trigger
            id:
              - left-pressed
        sequence: !input left_short

      # left press
      - conditions:
          - condition: trigger
            id:
              - right-pressed
        sequence: !input right_short

mode: restart
